# Deployment Target
platform :ios, '13.0'
install! 'cocoapods', :warn_for_unused_master_specs_repo => false

# Add pods as frameworks so we could add obj-c and swift 3.0 pods
use_frameworks!

target 'BaseClasses_Example' do
  pod 'APExtensions', :git => 'https://github.com/APUtils/APExtensions', :branch => 'master'
  pod 'BaseClasses', :path => '../'
  pod 'KeyboardAvoidingView', :git => 'https://github.com/APUtils/KeyboardAvoidingView', :branch => 'master'
  pod 'StretchScrollView', :git => 'https://github.com/APUtils/StretchScrollView', :branch => 'master'
  
  target 'BaseClasses_Tests' do
    inherit! :search_paths
    
    pod 'Quick'
    pod 'Nimble'
    pod 'Nimble-Snapshots'
  end
end

post_install do |installer|
  # Add podInstall.command and podUpdate.command shell scripts to Pods project
  pods_project = installer.pods_project
  pods_project.new_file "../Scripts/Cocoapods/podInstall.command"
  pods_project.new_file "../Scripts/Cocoapods/podUpdate.command"
  
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
